### ISSUE TITLE
OpenSSL Issue on OS X

### ISSUE THREAD

**Issue by ohayon** [stephan-nordnes-eriksen/ruby_ship#10]
Hey @stephan-nordnes-eriksen! Thank you for building this, it is really awesome so far.

I am running into an issue where, when calling a gem's binary from inside the `ruby_ship` directory, everything works fine. But if I try to execute one of those binaries in `.../ruby_ship/bin/shipyard/darwin_ruby/bin/<binary>` I get the following error output: 

```
/Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle, 9): Library not loaded: bin/shipyard/darwin_ruby/dylibs/libssl.1.0.0.dylib (LoadError)
  Referenced from: /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle
  Reason: image not found - /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/openssl.rb:13:in `<top (required)>'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon.rb:6:in `<top (required)>'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/gems/2.3.0/gems/fastlane_core-0.37.0/lib/fastlane_core/update_checker/update_checker.rb:1:in `<top (required)>'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/gems/2.3.0/gems/fastlane_core-0.37.0/lib/fastlane_core.rb:6:in `<top (required)>'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/gems/2.3.0/gems/fastlane-1.66.0/lib/fastlane.rb:18:in `<top (required)>'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/gems/2.3.0/gems/fastlane-1.66.0/bin/fastlane:6:in `<top (required)>'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/bin/fastlane:23:in `load'
    from /Users/dohayon/Twitter/git/ruby_ship/bin/shipyard/darwin_ruby/bin/fastlane:23:in `<main>'
```

Its also worth noting that I am using version 2.3.0 compiled with `ruby_ship_build.sh`.

Thanks!

**Comment by stephan-nordnes-eriksen** [comment]
I have not yet tried the newer versions of ruby with this, but there have been some problems relating to libssl. It has to do with linking and including the correct binaries. I have made a script which should take care of this [auto_relink_dylibs.rb](https://github.com/stephan-nordnes-eriksen/ruby_ship/blob/master/tools/auto_relink_dylibs.rb). Can you try to run the [implementation_tests.rb](https://github.com/stephan-nordnes-eriksen/ruby_ship/blob/master/tools/implementation_tests.rb) and see what you get? 

 `bin/ruby_ship.sh tools/implementation_tests.rb`.

FYI: have you checked out https://github.com/stephan-nordnes-eriksen/ruby_ship/issues/5?

**Comment by stephan-nordnes-eriksen** [comment]
Yeah, 

I think actually it will never work to run the binaries from outside the root folder. They are linked relative to this root folder. It is, as far as I am aware, the only possible way to make these binaries portable. 

If you need to run some of the binaries from outside this folder, you could possibly do this:

`$ cd path/to/ruby_ship/; bin/shipyard/darwin_ruby/bin/<binary> params; cd -`
