### ISSUE TITLE
Ruby gem issue (and solution) on Windows

### ISSUE THREAD

**Issue by flartet** [stephan-nordnes-eriksen/ruby_ship#14]
Hello,
first of all of course, thanks for your work from a portable apps lover.

On Windows 7 x64, I unzipped the full repo and began with 
`ruby_ship_gem install compass
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - X:/.gem`
It matches with a guess about homedir

Following this topic : https://github.com/rubygems/rubygems/issues/687
I first added in ruby_ship_gem.bat GEM_HOME and GEM_PATH but this doesn't change anything.
`set GEM_HOME=MYPATH\ruby_ship_master\gems
set GEM_PATH=MYPATH\ruby_ship_master\gems`

After that, I saw the option --no-user-install (user-install seems to be the default) but the option is not recognized.
Then, adding the third option
`set GEM_SPEC_CACHE=c:\ProgrammesFixes\ruby_ship_master\gems\specs`
it works.

At the moment, I added the 3 variables in each bin\*bat file, maybe you have a best answer to that : env dedicated file for example, that's why I'm not suggesting a pull request.

You know everything.

**Comment by stephan-nordnes-eriksen** [comment]
Thank you so much @flartet!

Unfortunately I do not have a windows machine available right now to test this, but I suspect that your problem might be related to admin privileges.

Have you tried running your CMD window "as administrator"? (right click and "run as administrator" or something). This might resolve your issue. If this does not resolve the problem then it is a bit hard for me to debug right now. 

If adding `GEM_SPEC_CACHE` solves the issue, then you should try to add it as a relative path so that it can be used generally. I remember struggling a bit with the`GEM_HOME` some platforms. Maybe I didn't do it right on Windows.

If you have a look at the OSx gem file inside the shipyard [darwin_gem.sh](https://github.com/stephan-nordnes-eriksen/ruby_ship/blob/master/bin/shipyard/darwin_gem.sh). It has some trickery going on to make the `GEM_HOME` and `GEM_PATH` work properly. Maybe you can experiment and see if you are able to get a similar solution for Windows? That would be great!

**Comment by flartet** [comment]
No, it's not from admin rights. I have the bad practice to have superuser rights by default and I also tried as you said with "as administrator".
On the thread I shared they are explaining that --user-install is default in .gemrc ; maybe it is the same behaviour even without .gemrc with your package.
The user "xfer" says : "If you don’t specify a value for GEM_SPEC_CACHE, it will use ~/.gem/specs (it doesn’t matter if I’m using --user-install or not)."
It seems to be ruby gems default behaviour.

Your script (with my environment variables patches) :
`C:\ProgrammesFixes\ruby_ship>bin\ruby_ship.bat tools\implementation_tests.rb
Test success: 1
Test success: 2
Test success: 3
C:/ProgrammesFixes/ruby_ship/bin/shipyard/win_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- bundler (LoadError)
        from C:/ProgrammesFixes/ruby_ship/bin/shipyard/win_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from tools/implementation_tests.rb:75:in 'block in <main>'
        from tools/implementation_tests.rb:88:in 'call'
        from tools/implementation_tests.rb:88:in 'block in <main>'
        from tools/implementation_tests.rb:86:in 'each'
        from tools/implementation_tests.rb:86:in 'each_with_index'
        from tools/implementation_tests.rb:86:in '<main>'`

**Comment by stephan-nordnes-eriksen** [comment]
Do you get the same results without your fix as well? 

Perhaps you are not using existing windows ruby that comes bundled in? I suspect that bundler isn't properly installed. If this is in the pre-bundled version, then it has to be resolved. Again; I am without a windows computer currently (due to location), so I can't really investigate efficiently. 

Maybe you could try to create a new build of ruby for windows following the somewhat short guide here: https://github.com/stephan-nordnes-eriksen/ruby_ship/issues/3 ?

**Comment by flartet** [comment]
Good feeling, I removed my env variables and
`C:\ProgrammesFixes\ruby_ship>bin\ruby_ship.bat tools\implementation_tests.rb
Test success: 1
Test success: 2
Test success: 3
Test success: 4
-----------RESULTS-----------
All tests succeeded. Ruby ship is ready to sail!`

The thing is I have never developed anything in ruby in my entire life. I installed it during a working session and I'll have to use compass - maybe - twice a year :)
But, when this moment will come, I promise I'll try to spend some time on your package.
