### ISSUE TITLE
Error running gem on CentOS

### ISSUE THREAD

**Issue by sumitag** [stephan-nordnes-eriksen/ruby_ship#18]
```
/root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/yaml.rb:4:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': libyaml-0.so.2: cannot open shared object file: No such file or directory - /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/i686-linux/psych.so (LoadError)
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/psych.rb:1:in `<top (required)>'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/yaml.rb:5:in `<top (required)>'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems.rb:616:in `load_yaml'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/config_file.rb:328:in `load_file'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/config_file.rb:197:in `initialize'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/gem_runner.rb:74:in `new'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/gem_runner.rb:74:in `do_configuration'
        from /root/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/gem_runner.rb:39:in `run'
        from /root/ruby_ship/bin/shipyard/linux_ruby/bin/gem:25:in `<main>'
```

**Comment by stephan-nordnes-eriksen** [comment]
What are you trying to do? What commands are you running?

**Comment by stephan-nordnes-eriksen** [comment]
Can you try to run `$ bin/ruby_ship.sh tools/implementation_tests.rb` from the project root? I don't have much experience with CentOS, but I suspect that you installed gem which you do not have all the required development tools available.

**Comment by sumitag** [comment]
```
/test/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': libssl.so.1.0.0: cannot open shared object file: No such file or directory - /test/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/i686-linux/openssl.so (LoadError)
        from /test/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /test/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/openssl.rb:17:in `<top (required)>'
        from /test/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /test/ruby_ship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from tools/implementation_tests.rb:29:in `block in <main>'
        from tools/implementation_tests.rb:88:in `call'
        from tools/implementation_tests.rb:88:in `block in <main>'
        from tools/implementation_tests.rb:86:in `each'
        from tools/implementation_tests.rb:86:in `each_with_index'
        from tools/implementation_tests.rb:86:in `<main>'
```

**Comment by alexandrosdelta** [comment]
The first missing `libyaml-0.so.2` appears when simply running `ruby_ship_gem.sh`.
```
/rubyship>bin/ruby_ship_gem.
/rubyship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/yaml.rb:4:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/rubyship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': libyaml-0.so.2: cannot open shared object file: No such file or directory - /rubyship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/i686-linux/psych.so (LoadError)
...
```
Running the `implementation_tests.rb` gives a similar missing library error for OpenSSL.
```
/rubyship>bin/ruby_ship.sh  tools/implementation_tests.rb
/rubyship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': libssl.so.1.0.0: cannot open shared object file: No such file or directory - /rubyship/bin/shipyard/linux_ruby/lib/ruby/2.1.0/i686-linux/openssl.so (LoadError)
...
```

CentOS minimal ISO does not have libyaml or openssl, and it seems that ruby_ship does not include them.
How can these libraries be included?

**Comment by stephan-nordnes-eriksen** [comment]
Interesting.

I had similar issues with OSx. The solution there was to actually bundle up dylibs. There is a whole part of this repo which deals with relinking dylibs. Parts of that might be re-usable to a certain extent to do the same with the `.so` files for centos (and others?).

Since I made this library a while back I have become more competent with things like Docker, so I can see if I can duplicate the issue and perhaps resolve it, but I would also like to note that I am currently in a very hectic period at my work, so it might be some days until I can have a look at this.
